### ISSUE TITLE
DHSVM versioning  - do we have a 3.1.3??

### ISSUE THREAD

**Issue by ChristinaB** [pnnl/DHSVM-PNNL#2]
Hi Ning,
SeYeun and I are working on code that Chris developed with the glacier integration with RBM.  I would like to have others download and install this code directly from Github, but am unclear on the latest version.  The sourcecode I have generates 3.1.3 executable, but your glacier branch still lists 3.1.2.  Do you plan on merging the glacier branch with Master? 
Thanks for all your work!
Christina

**Comment by Lizzy0Sun** [comment]
Hi Christina,

The glacier version won't be merged to the master branch for the time being. We are working on DHSVM parallelization using the master version, so we will keep the master branch the way it is until the parallelization version fully pass the tests. For now, I'd suggest download the glacier version directly from the branch. Thanks.
