### ISSUE TITLE
Suggested Changes to "MM5" Met Input

### ISSUE THREAD

**Issue by wperkins** [pnnl/DHSVM-PNNL#27]
I propose some changes to the `[MM5]` met input:
1.  _Terrain_: Currently, the `MM5 Terrain File` must contain an elevation map for _every_ simulation time step. This seems unnecessary. I propose one of
     1. Just assume the  `MM5 Terrain File` be assumed constant, and so it's only read once; or
     2. Add a new `[MM5]` phrase, `MM5 Terrain File Frequency`, with the following choices:
         - `single`: A single map of lapse rate held constant through the simulation; 
         - `continuous`: One map for each time step, as it is now.

     I prefer the former.
2. _Temperature Lapse_: The `MM5 Temp Lapse File` must also contain a lapse rate map for _every_ simulation time step.  This seems unnecessary.  I propose the following modifications:
    1.  `MM5 Temp Lapse File = none`  be the default, in which case the specified `Temperature Lapse Rate` in `[CONSTANTS]` is used basin-wide.  
    2.  When `MM5 Temp Lapse File` is specified, I propose a frequency option be added to handle this map in a manner similar to the `MM5 Precipitation Distribution File`.  A new `[MM5]` phrase `MM5 Temperature Lapse Frequency` would be added with the following choices:
        - `single`: A single map of lapse rate held constant through the simulation;
        - `month`: A set of 12 maps of lapse rate, one for each month of the year; and
        - `continuous`: One map for each time step, as it is now.

Thoughts?

**Comment by Lizzy0Sun** [comment]
As the elevation map doesn't change at each simulation time step, i agree we just make it a constant and let the program read it once and for all as you suggested in 1.1. I haven't use the MM5 option so I added Zhuoran to review your proposed change.

**Comment by zrduan** [comment]
@wperkins  I agree with you.

For the terrain file I think one input layer is sufficient to cover most of the applications and represent the meteorology data terrain. 

For temperature lapse file, I think the 4 options you have listed meets different types of user needs. And having the constant lapse rate value set as default option provides a efficient workflow for calibration and for cases where spatial varied lapse rates are not needed.

**Comment by Lizzy0Sun** [comment]
@wperkins  I say go ahead with the code modification as you suggested above.

**Comment by zrduan** [comment]
@wperkins On second thought about the lapse rate - could the spatial varied lapse rate an option in both [CONSTANTS] section and the [MM5] section?

**Comment by wperkins** [comment]
> @wperkins On second thought about the lapse rate - could the spatial varied lapse rate an option in both [CONSTANTS] section and the [MM5] section?

@zrduan So, you want temperature lapse to be a "mapped" constant like the snow parameters.  I made a separate issue (#28) for this.  If `MM5 Temp Lapse File = none` then the temperature lapse would be handled as defined in `[CONSTANTS]`.

**Comment by zrduan** [comment]
@wperkins Yes. I think it's helpful to have spatial varied temperature lapse but independent from the MM5 format.

**Comment by wperkins** [comment]
Can we keep this open until the changes are actually made?
