### ISSUE TITLE
Error in link to documentation : 

### ISSUE THREAD

**Issue by deliott** [pnnl/DHSVM-PNNL#45]
Hello, 
I think the link to dhsvm documentation is wrong. 
When I click on the link I am directed toward : http://dhsvmdev.pnl.gov///  (which apparently doesn't exist)

Whereas I found this documentation elsewhere https://dhsvm.pnnl.gov/tutorials.stm

**Comment by zrduan** [comment]
Thank you for your feedback! We have updated the external link to the DHSVM website.
